# Generated by Django 5.0.1 on 2024-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_new_project', 'can add new project'), ('dg_view_project', 'OLP can view project')]},
        ),
    ]
